// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: ledger/ledger.proto

package ledger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "debit" or "credit"
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEntryRequest) Reset() {
	*x = RecordEntryRequest{}
	mi := &file_ledger_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEntryRequest) ProtoMessage() {}

func (x *RecordEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEntryRequest.ProtoReflect.Descriptor instead.
func (*RecordEntryRequest) Descriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *RecordEntryRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RecordEntryRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *RecordEntryRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RecordEntryRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type RecordEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EntryId       string                 `protobuf:"bytes,2,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEntryResponse) Reset() {
	*x = RecordEntryResponse{}
	mi := &file_ledger_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEntryResponse) ProtoMessage() {}

func (x *RecordEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEntryResponse.ProtoReflect.Descriptor instead.
func (*RecordEntryResponse) Descriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *RecordEntryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordEntryResponse) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

var File_ledger_ledger_proto protoreflect.FileDescriptor

const file_ledger_ledger_proto_rawDesc = "" +
	"\n" +
	"\x13ledger/ledger.proto\x12\x06ledger\"\x84\x01\n" +
	"\x12RecordEntryRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\"J\n" +
	"\x13RecordEntryResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\bentry_id\x18\x02 \x01(\tR\aentryId2W\n" +
	"\rLedgerService\x12F\n" +
	"\vRecordEntry\x12\x1a.ledger.RecordEntryRequest\x1a\x1b.ledger.RecordEntryResponseB*Z(github.com/emzhofb/gowallet/proto/ledgerb\x06proto3"

var (
	file_ledger_ledger_proto_rawDescOnce sync.Once
	file_ledger_ledger_proto_rawDescData []byte
)

func file_ledger_ledger_proto_rawDescGZIP() []byte {
	file_ledger_ledger_proto_rawDescOnce.Do(func() {
		file_ledger_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ledger_ledger_proto_rawDesc), len(file_ledger_ledger_proto_rawDesc)))
	})
	return file_ledger_ledger_proto_rawDescData
}

var file_ledger_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ledger_ledger_proto_goTypes = []any{
	(*RecordEntryRequest)(nil),  // 0: ledger.RecordEntryRequest
	(*RecordEntryResponse)(nil), // 1: ledger.RecordEntryResponse
}
var file_ledger_ledger_proto_depIdxs = []int32{
	0, // 0: ledger.LedgerService.RecordEntry:input_type -> ledger.RecordEntryRequest
	1, // 1: ledger.LedgerService.RecordEntry:output_type -> ledger.RecordEntryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ledger_ledger_proto_init() }
func file_ledger_ledger_proto_init() {
	if File_ledger_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ledger_ledger_proto_rawDesc), len(file_ledger_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ledger_ledger_proto_goTypes,
		DependencyIndexes: file_ledger_ledger_proto_depIdxs,
		MessageInfos:      file_ledger_ledger_proto_msgTypes,
	}.Build()
	File_ledger_ledger_proto = out.File
	file_ledger_ledger_proto_goTypes = nil
	file_ledger_ledger_proto_depIdxs = nil
}
